import { Varela_Round } from "next/font/google";
import "../styles/globals.css";

const varela = Varela_Round({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-varela",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={varela.variable}>
        {children}
      </body>
    </html>
  );
}
